-- ============================================================
--  File:    supabase-seed.sql
--  Purpose: Example data for every table in the Pendleton
--           Plantation schema. Use this as a formatting
--           reference when adding real entries via the admin
--           panel or SQL editor.
--
--  HOW TO USE:
--    1. Go to your Supabase project → SQL Editor
--    2. Paste this file and click "Run"
--    3. All inserts use ON CONFLICT DO NOTHING so it is safe
--       to run multiple times without creating duplicates.
--
--  NOTES:
--    • profiles is auto-created by trigger on auth.users;
--      there is no manual example here.
--    • config, links, and documents are already seeded in
--      supabase-schema.sql; examples below are for reference only.
--    • signups uses user_id = NULL for guest submissions
--      (no account required). This is intentional and expected.
--    • photo_urls is a TEXT[] array — use the ARRAY[...] syntax
--      or '{}' for empty.  URLs are Google Drive share links.
--    • ics_start / ics_end are plain TEXT in iCal format:
--      'YYYYMMDDTHHMMSS' (no timezone suffix needed).
-- ============================================================


-- ============================================================
--  CONFIG  (key-value site settings)
--  Already seeded in supabase-schema.sql.  Listed here for
--  reference only — shows every key the site reads.
-- ============================================================
/*
INSERT INTO config (key, value) VALUES
  ('organizer_name',   'Pendleton Plantation HOA'),
  ('organizer_email',  'board@pendletonplantation.com'),
  ('organizer_phone',  '(864) 555-0100'),
  ('current_event_id', 'SummerBlockParty2026')  -- must match an events.id slug
ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value;
*/


-- ============================================================
--  EVENTS
--  id:                 Alphanumeric slug — NO spaces or special
--                      characters.  Generated by autoSlug() in
--                      the admin panel from the event name.
--  status:             'Confirmed' | 'Draft' | 'Cancelled'
--  event_date:         DATE  e.g. '2026-07-04'
--  event_time:         Plain text e.g. '5:00 PM – 9:00 PM'
--  signups_open_date:  DATE — when the sign-up form unlocks
--  banner_color_class: 'card-color-1' (Teal)
--                      'card-color-2' (Blue)
--                      'card-color-3' (Purple)
--                      'card-color-4' (Green)
--                      'card-color-5' (Gold)
--                      'card-color-6' (Navy)
--  emoji_row:          Decorative emoji string shown in banner
--  headline_adjective: One word that fills in "A [word] Evening"
--  ics_start / ics_end: iCal format 'YYYYMMDDTHHMMSS'
-- ============================================================
INSERT INTO events (
  id, event_name, status,
  event_date, event_time, signups_open_date,
  short_description, medium_description, long_description,
  emoji_row, headline_adjective,
  location_name, location_address,
  banner_color_class,
  ics_start, ics_end,
  organizer_name, organizer_email, organizer_phone,
  organizer_address, organizer_contact
) VALUES (
  'SummerBlockParty2026',              -- id (slug, no spaces)
  'Summer Block Party 2026',           -- event_name
  'Confirmed',                         -- status: 'Confirmed' | 'Draft' | 'Cancelled'
  '2026-07-04',                        -- event_date
  '5:00 PM – 9:00 PM',               -- event_time
  '2026-06-01',                        -- signups_open_date
  'Join your neighbors for our annual Fourth of July block party!',
  'Celebrate the holiday with food, fun, and fireworks. Bring a dish to share and enjoy an evening with your Pendleton Plantation neighbors.',
  'Our annual Summer Block Party is back! We''ll have grilled favorites, a potluck spread, yard games, and a front-row seat for fireworks. Families of all sizes are welcome. Sign up to RSVP, volunteer, or donate a dish.',
  '🎆🌟🎉🌟🎆',                       -- emoji_row (decorative banner text)
  'Festive',                           -- headline_adjective
  'Pendleton Plantation Pool & Pavilion',
  '100 Pendleton Way, Easley, SC 29642',
  'card-color-6',                      -- banner_color_class: card-color-1 through card-color-6
  '20260704T170000',                   -- ics_start (iCal: YYYYMMDDTHHMMSS)
  '20260704T210000',                   -- ics_end
  'Pendleton Plantation HOA',
  'board@pendletonplantation.com',
  '(864) 555-0100',
  '100 Pendleton Way, Easley, SC 29642',
  'Email'                              -- organizer_contact: 'Email' | 'Phone'
)
ON CONFLICT (id) DO NOTHING;


-- ============================================================
--  EVENT VOLUNTEER ROLES
--  Linked to events.id.  sort_order controls display order.
-- ============================================================
INSERT INTO event_volunteer_roles (event_id, role_label, role_detail, sort_order) VALUES
  ('SummerBlockParty2026', 'Grill Master',      'Manage the grills and keep the food coming!', 0),
  ('SummerBlockParty2026', 'Setup Crew',         'Help set up tables, chairs, and decorations starting at 3 PM.', 1),
  ('SummerBlockParty2026', 'Games Coordinator',  'Run the yard game stations and keep the fun going.', 2),
  ('SummerBlockParty2026', 'Cleanup Crew',       'Help break down and clean up after the event.', 3)
ON CONFLICT DO NOTHING;


-- ============================================================
--  EVENT DONATION ITEMS
--  Grouped by category.  sort_order controls display order
--  within each category.  qty_needed = NULL means "any amount".
-- ============================================================
INSERT INTO event_donation_items (event_id, category, item_label, qty_needed, sort_order) VALUES
  ('SummerBlockParty2026', 'Food & Drinks', 'Bag of ice',         10,   0),
  ('SummerBlockParty2026', 'Food & Drinks', 'Case of water',       8,   1),
  ('SummerBlockParty2026', 'Food & Drinks', 'Bag of charcoal',     4,   2),
  ('SummerBlockParty2026', 'Supplies',      'Folding table',        5, 100),
  ('SummerBlockParty2026', 'Supplies',      'Box of paper plates', 6,  101),
  ('SummerBlockParty2026', 'Supplies',      'Plastic utensil set',  6, 102)
ON CONFLICT DO NOTHING;


-- ============================================================
--  SIGNUPS
--  user_id = NULL is normal for guests (no account required).
--  archived = FALSE means "active / not yet rolled over".
--  attending: free-text from the form, e.g. 'Yes – our whole family'
-- ============================================================
INSERT INTO signups (
  event_id, user_id,
  first_name, last_name, email, phone, address,
  attending, num_adults, num_children,
  children_0_3, children_4_8, children_9_plus,
  potluck_item, other_donation, cash_donation,
  notes, heard_about, special_skills,
  opt_in_events, opt_in_newsletter, archived
) VALUES (
  'SummerBlockParty2026',
  NULL,                                -- NULL = guest submission (no account)
  'Jane', 'Smith',
  'jane.smith@example.com',
  '(864) 555-0199',
  '42 Magnolia Lane, Easley, SC 29642',
  'Yes – our whole family',
  2,                                   -- num_adults
  2,                                   -- num_children
  0,                                   -- children_0_3
  1,                                   -- children_4_8
  1,                                   -- children_9_plus
  'Macaroni salad',                    -- potluck_item
  'A case of water',                   -- other_donation
  NULL,                                -- cash_donation
  'We''ll arrive around 5:30.',        -- notes
  'Neighborhood Facebook group',       -- heard_about
  'Face painting',                     -- special_skills
  TRUE,                                -- opt_in_events
  FALSE,                               -- opt_in_newsletter
  FALSE                                -- archived
);

-- Capture the signup id for use in join tables below
-- (Run the join-table inserts immediately after, in the same session)
DO $$
DECLARE v_signup_id BIGINT;
BEGIN
  SELECT id INTO v_signup_id
  FROM signups
  WHERE email = 'jane.smith@example.com'
    AND event_id = 'SummerBlockParty2026'
  ORDER BY submitted_at DESC
  LIMIT 1;

  IF v_signup_id IS NOT NULL THEN

    -- signup_volunteer_roles: roles this person signed up for
    INSERT INTO signup_volunteer_roles (signup_id, role_label) VALUES
      (v_signup_id, 'Cleanup Crew')
    ON CONFLICT DO NOTHING;

    -- signup_donation_items: items this person pledged
    INSERT INTO signup_donation_items (signup_id, item_label, qty_pledged) VALUES
      (v_signup_id, 'Case of water', 1)
    ON CONFLICT DO NOTHING;

  END IF;
END $$;


-- ============================================================
--  ANNOUNCEMENTS
--  day / month: short strings for the date badge, e.g. '4', 'July'
--  published = TRUE makes the post visible to the public.
-- ============================================================
INSERT INTO announcements (day, month, title, body, link, link_text, published) VALUES
  ('4',  'July',
   'Summer Block Party — Save the Date!',
   'Mark your calendars! The annual Pendleton Plantation Summer Block Party is coming up on July 4th. Sign-ups open June 1st. Bring the family, bring a dish, and bring your spirit!',
   'signup.html?event=SummerBlockParty2026',
   'Sign Up Now',
   TRUE),

  ('15', 'May',
   'Pool Now Open for the Season',
   'The Pendleton Plantation pool is officially open for the 2026 season. Reminder: all guests must be accompanied by a resident. Pool rules are posted at the gate and available in the Documents section.',
   'documents.html',
   'View Pool Rules',
   TRUE),

  ('1',  'June',
   'Yard of the Month — Nominations Open',
   'Know a neighbor with a beautiful yard? Nominate them for Yard of the Month! Nominations are open all month. Winners receive a yard sign and a small gift card.',
   'awards.html',
   'Submit a Nomination',
   TRUE)
ON CONFLICT DO NOTHING;


-- ============================================================
--  AWARD CONTESTS
--  id:          Alphanumeric slug (no spaces).
--  banner_color: 'banner-gold'  | 'banner-green' | 'banner-blue'
--               'banner-navy'  | 'banner-red'   | 'banner-purple'
--  status:      'open'         → nominations accepted (green pill)
--               'soon'         → coming up (gold pill)
--               'voting'       → community voting open (blue pill)
--               'deliberating' → closed, committee reviewing (bronze pill)
--               'awarded'      → winner announced (navy pill)
--  category:    'Yard & Garden' | 'Community' | 'Service'
--               'Events'       | 'Youth'
--  deadline:    Plain text shown on card, e.g. 'June 30, 2026'
--  prize:       Plain text, e.g. '$25 gift card + yard sign'
-- ============================================================
INSERT INTO award_contests (
  id, icon, badge, banner_color,
  award_name, category, period,
  status, description, deadline, prize
) VALUES
  (
    'YardOfTheMonth2026Jun',           -- id slug
    '🌿',                              -- icon (emoji)
    '',                                -- badge (image path, optional)
    'banner-green',                    -- banner_color
    'Yard of the Month',               -- award_name
    'Yard & Garden',                   -- category
    'June 2026',                       -- period
    'open',                            -- status
    'Celebrate the beautiful yards that make Pendleton Plantation shine! Nominate a neighbor whose landscaping, flowers, or curb appeal stands out this month.',
    'June 30, 2026',                   -- deadline
    '$25 gift card + yard sign'        -- prize
  ),
  (
    'NeighborhoodHero2026Q2',
    '🦸',
    '',
    'banner-gold',
    'Neighborhood Hero Award',
    'Community',
    'Spring 2026',
    'soon',
    'Recognizes a resident who consistently goes above and beyond for the Pendleton Plantation community. Nominations open in May.',
    '',                                -- no deadline yet
    'Framed certificate + feature in newsletter'
  ),
  (
    'SeasonalDecor2025Winter',
    '❄️',
    '',
    'banner-navy',
    'Holiday Décor Contest',
    'Events',
    'Winter 2025',
    'awarded',                         -- already awarded
    'Our annual holiday decorating contest. Thank you to everyone who participated — the neighborhood looked absolutely beautiful!',
    '',
    '$50 gift card'
  )
ON CONFLICT (id) DO NOTHING;


-- ============================================================
--  AWARD NOMINATIONS
--  contest_id references award_contests.id (nullable — stays
--  if the contest is later deleted).
--  user_id = NULL is fine; guests can nominate without an account.
--  photo_urls: TEXT[] of Google Drive share URLs (can be empty).
-- ============================================================
INSERT INTO award_nominations (
  contest_id, user_id,
  nominator_name, nominator_phone, nominator_email, nominator_address,
  nominee_name, nominee_address,
  award_category, custom_award,
  reasons, photo_urls, approved
) VALUES (
  'YardOfTheMonth2026Jun',
  NULL,                                -- NULL = guest nomination (no account)
  'Robert Johnson',
  '(864) 555-0144',
  'robert.johnson@example.com',
  '18 Oak Hollow Drive, Easley, SC 29642',
  'The Williams Family',
  '7 Dogwood Circle, Easley, SC 29642',
  'Yard & Garden',                     -- award_category (matches contest category)
  NULL,                                -- custom_award (used when category = 'Other')
  'Their rose garden is absolutely stunning this year. They also added a gorgeous Japanese maple along the front walk. The whole street benefits from their care.',
  ARRAY[]::TEXT[],                     -- photo_urls: empty array, or ARRAY['https://drive.google.com/...']
  FALSE                                -- approved (admin must approve)
)
ON CONFLICT DO NOTHING;


-- ============================================================
--  WINNERS
--  contest_id: references award_contests.id (nullable)
--  photo_id:   Google Drive file ID (the long alphanumeric string
--              from a Drive share URL — NOT the full URL)
--              e.g. '1a2B3c4D5e6F7g8H9i0J' from
--              'https://drive.google.com/file/d/1a2B3c4D5e6F7g8H9i0J/view'
--  banner_color: same values as award_contests.banner_color
--  year:       Four-digit year as TEXT e.g. '2025'
-- ============================================================
INSERT INTO winners (
  contest_id, icon, badge, banner_color,
  award, period, year,
  winner_name, photo_id,
  prize, blurb,
  quote1, quote2, quote3
) VALUES
  (
    'SeasonalDecor2025Winter',         -- contest_id (must exist in award_contests)
    '❄️',
    '',
    'banner-navy',
    'Holiday Décor Contest',           -- award (display name on the card)
    'Winter 2025',                     -- period
    '2025',                            -- year
    'The Martinez Family',             -- winner_name
    NULL,                              -- photo_id (Google Drive file ID, or NULL)
    '$50 gift card',                   -- prize
    'The Martinez family transformed their home into a winter wonderland — complete with synchronized lights, a sleigh display, and hand-painted nutcrackers lining the walkway.',
    'We started decorating right after Thanksgiving and it became a whole family project!',
    'The neighborhood kids would stop every evening just to watch the lights.',
    NULL                               -- quote3 (optional third quote)
  ),
  (
    NULL,                              -- contest_id NULL = manually added, not tied to a contest
    '🌿',
    '',
    'banner-green',
    'Yard of the Month',
    'May 2026',
    '2026',
    'The Chen Family',
    NULL,
    '$25 gift card + yard sign',
    'Exceptional curb appeal with a blooming azalea border and freshly mulched beds.',
    'Gardening is our therapy — we love seeing neighbors enjoy it too.',
    NULL,
    NULL
  )
ON CONFLICT DO NOTHING;


-- ============================================================
--  WINNER PREP  (staging table — rows here have NOT been
--  promoted to winners yet)
--  Populated automatically when admin uses "Promote" from a
--  nomination, or can be inserted manually for testing.
--  promoted = FALSE means it's still in the queue.
-- ============================================================
INSERT INTO winner_prep (
  nomination_id,
  award, winner_name, blurb,
  quote1, quote2, quote3,
  full_reasons_text, nominator_name,
  icon, badge, banner_color,
  period, year, photo_id, prize,
  promoted
) VALUES (
  NULL,                                -- nomination_id (NULL if not from a nomination)
  'Neighborhood Hero Award',
  'Susan Taylor',
  'Susan organized three neighborhood clean-up days this spring, personally recruited 30+ volunteers, and donated supplies from her own pocket.',
  'A community only works when neighbors show up for each other.',
  NULL,
  NULL,
  'Susan has been an incredible force this year — she organized clean-ups, helped new families move in, and kept everyone connected via the neighborhood group.',
  'David Kim',                         -- nominator_name
  '🦸',
  '',
  'banner-gold',
  'Spring 2026',
  '2026',
  NULL,                                -- photo_id
  'Framed certificate + feature in newsletter',
  FALSE                                -- promoted = FALSE (still in staging)
)
ON CONFLICT DO NOTHING;


-- ============================================================
--  MEMORIES  (photo gallery submissions)
--  photo_urls: TEXT[] of Google Drive share URLs.
--  approved = TRUE makes the memory visible on the public gallery.
--  approved = FALSE means it awaits admin review.
-- ============================================================
INSERT INTO memories (
  user_id, uploader_name, email,
  event_name, caption,
  photo_urls, approved
) VALUES (
  NULL,                                -- user_id: NULL = guest upload (no account)
  'Lisa Park',
  'lisa.park@example.com',
  'Easter Egg Hunt 2026',
  'The kids had so much fun hunting for eggs in the common area! Perfect spring morning.',
  ARRAY[
    'https://drive.google.com/file/d/EXAMPLE_DRIVE_ID_1/view',
    'https://drive.google.com/file/d/EXAMPLE_DRIVE_ID_2/view'
  ],
  TRUE                                 -- approved: TRUE = visible publicly
)
ON CONFLICT DO NOTHING;


-- ============================================================
--  BULLETIN POSTS  (community board)
--  category options (free text — match what the form uses):
--    'General / Community News'
--    'For Sale / Free'
--    'Services Offered'
--    'Lost & Found'
--    'Safety Alert'
--    'Recommendation'
--    'Other'
--  show_phone / show_email: control whether contact info is
--    visible to the public (resident's choice on the form).
--  approved = TRUE makes the post visible on the public board.
-- ============================================================
INSERT INTO bulletin_posts (
  user_id, poster_name, email, phone, address,
  category, title, content,
  photo_urls, show_phone, show_email, approved
) VALUES
  (
    NULL,
    'Tom & Carol Bennett',
    'bennett.family@example.com',
    '(864) 555-0177',
    '23 Sycamore Drive, Easley, SC 29642',
    'For Sale / Free',
    'Free Hostas — Come Dig Your Own!',
    'We divided our hostas this spring and have plenty to give away. Mature clumps — great for shady areas. Come by Saturday morning or message us to arrange a time. No charge, just bring a shovel and a pot!',
    ARRAY[]::TEXT[],                   -- photo_urls: empty, or add Drive URLs
    TRUE,                              -- show_phone: TRUE = phone visible publicly
    FALSE,                             -- show_email: FALSE = email hidden publicly
    TRUE                               -- approved
  ),
  (
    NULL,
    'Mike Nguyen',
    'mike.nguyen@example.com',
    NULL,
    '5 Willow Creek Court, Easley, SC 29642',
    'Services Offered',
    'Lawn Mowing & Edging — Reasonable Rates',
    'Local teenager offering lawn care services this summer. Mowing, edging, and leaf blowing. References available. Message me for a quote — I''m trying to save up for college!',
    ARRAY[]::TEXT[],
    FALSE,
    TRUE,                              -- show_email = TRUE so neighbors can reach him
    TRUE
  )
ON CONFLICT DO NOTHING;


-- ============================================================
--  LINKS  (Community Resources page)
--  Already seeded in supabase-schema.sql.  Example below shows
--  the exact format to use when adding more.
--  sort_order: controls display order within each category.
-- ============================================================
/*
INSERT INTO links (category, icon, title, description, url, url_label, sort_order) VALUES
  ('Neighborhood Resources', '📋', 'My New Link', 'A short description of what this link is for.', 'https://example.com', 'example.com', 10)
ON CONFLICT DO NOTHING;
*/


-- ============================================================
--  DOCUMENTS  (Community Resources page)
--  Already seeded in supabase-schema.sql.  Example below shows
--  the exact format to use when adding more.
--  url_label: optional short label shown instead of the full URL.
-- ============================================================
/*
INSERT INTO documents (category, icon, title, description, url, url_label, sort_order) VALUES
  ('Neighborhood Documents — Click to Download', '📄', 'My New Document', 'What this document contains.', 'https://engage.goenumerate.com/s/pendletonplantation/files/...', '', 10)
ON CONFLICT DO NOTHING;
*/
